site_name: Estimate pi
nav:
    - Home: index.md
    - Package: estimate_pi.md
theme:
  name: "material"
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            docstring_style: "numpy"
            show_source: false
      custom_templates: templates
      watch:
        - src/estimate_pi
