site_name: Estimate pi
nav:
    - Home: index.md
    - Usage: usage.md
    - Code Reference: estimate_pi.md
theme:
  name: "material"
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            docstring_style: "numpy"
            show_source: false
      custom_templates: templates
      watch:
        - src/estimate_pi
